-d C:\Workspace\TangNano_DisplayDriver\impl\gwsynthesis\ram test.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Workspace\TangNano_DisplayDriver\src\top.cst
-cfg C:\Workspace\TangNano_DisplayDriver\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
